name = "gorlabs"
compatibility_date = "2024-11-12"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[vars]
NODE_VERSION = "18.18.0"

[observability]
enabled = true
head_sampling_rate = 1
