services:
  searxng:
    build:
      context: .
      dockerfile: searxng.dockerfile
    expose:
      - 4000
    ports:
      - 4000:8080
    networks:
      - memory

  memory-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    expose:
      - 3001
    ports:
      - 3001:3001
    networks:
      - memory

networks:
  memory:
