export const siteConfig = {
  name: 'gorlabs',
  siteDomain: 'gorlabs.com',
  titleTemplate: '%s | Gorlabs',
  url: 'https://gorlabs.com',
  ogImage: '/icons/krsna.png',
  keywords: [
    'Gorlabs',
    'gorlabs.com',
    'gor labs',
    'gorlab',
    'Gaurav',
    'gauravmandall',
    'github.com/gorlabscom',
    'github.com/gauravmandall',
    'saas',
    'opensource',
    'open source',
    'react',
    'nextjs',
    'hacktoberfest',
    'engineer',
    'founder',
    'web3',
    'Ai',
    'x.com/gorlabs',
    'x.com/gauravmandall',
    'bots',
    'web',
    'web development',
    'web design',
    'computer science',
  ],
  description: 'Making the web more beautiful, accessible, and fast.',
  links: {
    twitter: 'https://twitter.com/gauravmandall',
    github: 'https://github.com/gorlabscom/gorlabs',
  },
  creator: {
    name: 'Gaurav Mandal',
    url: 'https://gauravmandall.vercel.app',
  },
};

export type SiteConfig = typeof siteConfig;
